export const DOING_LOGIN = "DOING_LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const DOING_LOGOUT = "DOING_LOGOUT"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_ERROR = "LOGOUT_ERROR"

export const UPDATE_BALANCE = "UPDATE_BALANCE"
