
export const ADD_CHAT_SUCCESS = "ADD_CHAT_SUCCESS"
export const ADD_CHAT_ERROR = "ADD_CHAT_ERROR"
export const FETCHING_CHAT = "FETCHING_CHAT"
export const FETCHING_CHAT_ERROR = "FETCHING_CHAT_ERROR"
export const FETCHING_CHAT_SUCCESS = "FETCHING_CHAT_SUCCESS"