export const FETCHING_NOTIFICACIONES = "FETCHING_NOTIFICACIONES"
export const FETCHING_NOTIFICACIONES_SUCCESS = "FETCHING_NOTIFICACIONES_SUCCESS"
export const FETCHING_NOTIFICACIONES_ERROR = "FETCHING_NOTIFICACIONES_ERROR"