export const FETCHING_RESERVA = "FETCHING_RESERVA"
export const FETCHING_RESERVA_SUCCESS = "FETCHING_RESERVA_SUCCESS"
export const FETCHING_RESERVA_ERROR = "FETCHING_RESERVA_ERROR"

export const POST_RESERVA = "POST_RESERVA"
export const POST_RESERVA_SUCCESS = "POST_RESERVA"
export const POST_RESERVA_ERROR = "POST_RESERVA"
