export const FETCHING_TICKET = "FETCHING_TICKET"
export const FETCHING_TICKET_SUCCESS = "FETCHING_TICKET_SUCCESS"
export const FETCHING_TICKET_ERROR = "FETCHING_TICKET_ERROR"

export const ADD_TICKET_SUCCESS = "ADD_TICKET_SUCCESS"
export const ADD_TICKET_ERROR = "ADD_TICKET_ERROR"
