export const FETCHING_TRANSACTIONS = "FETCHING_TRANSACTIONS"
export const FETCHING_TRANSACTIONS_SUCCESS = "FETCHING_TRANSACTIONS_SUCCESS"
export const FETCHING_TRANSACTIONS_ERROR = "FETCHING_TRANSACTIONS_ERROR"