export const FETCHING_VEHICLES = "FETCHING_VEHICLE"
export const FETCHING_VEHICLES_SUCCESS = "FETCHING_VEHICLE_SUCCESS"
export const FETCHING_VEHICLES_ERROR = "FETCHING_VEHICLE_ERROR"

export const ADD_VEHICLE_SUCCESS = "ADD_VEHICLE_SUCCESS"
export const ADD_VEHICLE_ERROR = "ADD_VEHICLE_ERROR"

