export { default as LoginScreen } from './LoginScreen'
export { default as ArchivoAux } from './ArchivoAux'
export { default as MainScreen } from './MainScreen'
export { default as SignupScreen } from './SignupScreen'
export { default as NoPassScreen} from  './NoPassScreen'